# Travis CI script
version: ~> 1.0
import: nix-community/nix-travis-ci:nix.yml@main
#language: nix
#nix: 2.3.8

cache:
  directories:
    - $HOME/nix.store

before_install:
  - sudo mkdir -p /etc/nix
  - echo "substituters = https://cache.nixos.org/ file://$HOME/nix.store" | sudo tee -a /etc/nix/nix.conf > /dev/null
  - echo 'require-sigs = false' | sudo tee -a /etc/nix/nix.conf > /dev/null

before_cache:
  - mkdir -p $HOME/nix.store
  - nix copy --to file://$HOME/nix.store -f default.nix fil fseam tmxlite cppzmq sol3 chaiscript

before_script:
  - sudo mkdir -p /etc/nix && echo 'sandbox = true' | sudo tee /etc/nix/nix.conf