//
// Created by FyS on 3/7/19.
//

#ifndef PROXY_CLUSTER_DISPATCHER_VERSIONER_H
#define PROXY_CLUSTER_DISPATCHER_VERSIONER_H

// the configured options and settings for Tutorial
#define VERSION_MAJOR @VERSION_MAJOR @
#define VERSION_MINOR @VERSION_MINOR @

#endif//PROXY_CLUSTER_DISPATCHER_VERSIONER_H
